version: '3'
services:
  strapi:
    image: naskio/strapi
    restart: always
    container_name: strapi-v4
    ports:
      - '1337:1337'
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: false # boolean for SSL.
    volumes:
      - app:/srv/app # create a new project in app volume
    depends_on:
      - mysql

  mysql:
    restart: always
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    ports:
      - '3306:3306'  # 映射 MySQL 的端口
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  app: